export type SupportType = 'engage' | 'enchanter' | 'poke';
export type EnemyThreat = 'assassin' | 'tank' | 'poke';

export interface Champion {
  id: string;
  name: string;
  title: string;
  role: string[];
  difficulty: 'Low' | 'Medium' | 'High';
  image: string;
  imageSmall: string;
  tags: string[];
  synergies: SupportType[];
  counters: EnemyThreat[];
  description: string;
}

export interface SupportChampion {
  id: string;
  name: string;
  type: SupportType;
  image: string;
  imageSmall: string;
}



const CHAMPION_SQUARE_BASE_URL = "https://wiki.leagueoflegends.com/en-us/images/";
export function getChampionSquareIcon(name: string): string {
  const sanitizedName = name
    .replace(/\s+/g, "_")
    .replace(/[^A-Za-z0-9_']/g, "");
  const fileName = `${sanitizedName}_OriginalSquare.png`;
  return `${CHAMPION_SQUARE_BASE_URL}${encodeURIComponent(fileName)}`;
}

const adcBase: Array<Omit<Champion, "imageSmall">> = [
  {
    id: 'kaisa',
    name: "Kai'Sa",
    title: "Daughter of the Void",
    role: ["Marksman", "Assassin"],
    difficulty: "High",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kaisa_0.jpg",
    tags: ["High Mobility", "Burst", "Hybrid Damage"],
    synergies: ["engage"],
    counters: ["assassin", "tank"],
    description: "Excellent self-peel and dive potential. Great against assassins due to her ultimate shield and repositioning.",
  },
  {
    id: 'caitlyn',
    name: "Caitlyn",
    title: "The Sheriff of Piltover",
    role: ["Marksman"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Caitlyn_0.jpg",
    tags: ["Range", "Siege", "Lane Bully"],
    synergies: ["poke", "engage"],
    counters: ["poke"],
    description: "Dominates lane phase with range. Pairs well with heavy CC or poke supports to trap enemies.",
  },
  {
    id: 'ashe',
    name: "Ashe",
    title: "The Frost Archer",
    role: ["Marksman", "Support"],
    difficulty: "Low",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_0.jpg",
    tags: ["Utility", "CC", "Vision"],
    synergies: ["poke", "enchanter"],
    counters: ["tank"],
    description: "Utility queen. Global stun and constant slows make her great for kiting tanks and setting up plays.",
  },
  {
    id: 'jhin',
    name: "Jhin",
    title: "The Virtuoso",
    role: ["Marksman", "Mage"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jhin_0.jpg",
    tags: ["Utility", "Burst", "Sniper"],
    synergies: ["poke", "engage"],
    counters: ["poke"],
    description: "Utility ADC who brings CC and long range execution. Struggles against multiple tanks.",
  },
  {
    id: 'ezreal',
    name: "Ezreal",
    title: "The Prodigal Explorer",
    role: ["Marksman", "Mage"],
    difficulty: "High",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ezreal_0.jpg",
    tags: ["Poke", "Safe", "Mobility"],
    synergies: ["poke", "enchanter"],
    counters: ["assassin", "poke"],
    description: "The safest ADC pick. Good against assassins and poke lanes due to his E blink and long-range farming.",
  },
  {
    id: 'jinx',
    name: "Jinx",
    title: "The Loose Cannon",
    role: ["Marksman"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_0.jpg",
    tags: ["Hypercarry", "Reset", "Long Range"],
    synergies: ["enchanter", "engage"],
    counters: ["tank"],
    description: "The premier teamfight hypercarry. Needs protection but destroys tanks and teams once she gets a reset.",
  },
  {
    id: 'missfortune',
    name: "Miss Fortune",
    title: "The Bounty Hunter",
    role: ["Marksman"],
    difficulty: "Low",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MissFortune_0.jpg",
    tags: ["Lane Bully", "Teamfight", "Burst"],
    synergies: ["engage", "poke"],
    counters: ["tank"],
    description: "Strong laning phase and devastating ultimate. Works best with CC supports to land full Bullet Time.",
  },
  {
    id: 'smolder',
    name: "Smolder",
    title: "The Fiery Fledgling",
    role: ["Marksman", "Mage"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Smolder_0.jpg",
    tags: ["Scaling", "Poke", "Safe"],
    synergies: ["enchanter", "poke"],
    counters: ["assassin"],
    description: "Stack-based scaling ADC. Weak early but becomes a monster in late game. Needs protection.",
  },
  {
    id: 'lucian',
    name: "Lucian",
    title: "The Purifier",
    role: ["Marksman"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lucian_0.jpg",
    tags: ["Early Game", "Burst", "Mobility"],
    synergies: ["enchanter", "engage"],
    counters: ["assassin"],
    description: "Lane dominant burst caster. Needs to win early. Pairs exceptionally well with Nami.",
  },
  {
    id: 'sivir',
    name: "Sivir",
    title: "The Battle Mistress",
    role: ["Marksman"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sivir_0.jpg",
    tags: ["Waveclear", "Utility", "Teamfight"],
    synergies: ["engage", "enchanter"],
    counters: ["poke"],
    description: "Excellent waveclear and team utility with ult. Spellshield blocks key abilities.",
  },
  {
    id: 'vayne',
    name: "Vayne",
    title: "The Night Hunter",
    role: ["Marksman", "Assassin"],
    difficulty: "High",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vayne_0.jpg",
    tags: ["Tank Shred", "Duelist", "Late Game"],
    synergies: ["enchanter"],
    counters: ["tank"],
    description: "The ultimate tank killer. Weak laning phase, but unstoppable in the late game against high HP targets.",
  },
  {
    id: 'aphelios',
    name: "Aphelios",
    title: "The Weapon of the Faithful",
    role: ["Marksman"],
    difficulty: "High",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aphelios_0.jpg",
    tags: ["Complex", "Versatile", "Teamfight"],
    synergies: ["enchanter", "engage"],
    counters: ["assassin"],
    description: "Five weapon system allows for varied playstyles. Extremely high skill ceiling with great late game.",
  },
  {
    id: 'tristana',
    name: "Tristana",
    title: "The Yordle Gunner",
    role: ["Marksman", "Assassin"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Tristana_0.jpg",
    tags: ["All-in", "Reset", "Tower Siege"],
    synergies: ["engage", "enchanter"],
    counters: ["assassin"],
    description: "Strong all-in and tower taking. Good self-peel with ultimate and jump reset on kills.",
  },
  {
    id: 'varus',
    name: "Varus",
    title: "The Arrow of Retribution",
    role: ["Marksman", "Mage"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Varus_0.jpg",
    tags: ["Poke", "CC", "Mixed Damage"],
    synergies: ["poke", "engage"],
    counters: ["tank"],
    description: "Strong poke and CC with ultimate. Can be built lethality or on-hit depending on team needs.",
  },
  {
    id: 'draven',
    name: "Draven",
    title: "The Glorious Executioner",
    role: ["Marksman"],
    difficulty: "High",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Draven_0.jpg",
    tags: ["Lane Bully", "Snowball", "Early Game"],
    synergies: ["engage"],
    counters: ["poke"],
    description: "Highest early game damage. Needs to snowball leads. Gold passive rewards aggressive play.",
  },
  {
    id: 'xayah',
    name: "Xayah",
    title: "The Rebel",
    role: ["Marksman"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Xayah_0.jpg",
    tags: ["Self-Peel", "Burst", "Teamfight"],
    synergies: ["engage", "enchanter"],
    counters: ["assassin"],
    description: "Great self-peel with untargetable ultimate. Synergizes especially well with Rakan.",
  },
  {
    id: 'twitch',
    name: "Twitch",
    title: "The Plague Rat",
    role: ["Marksman", "Assassin"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Twitch_0.jpg",
    tags: ["Stealth", "Teamfight", "Late Game"],
    synergies: ["enchanter"],
    counters: ["assassin"],
    description: "Stealth assassin ADC. Weak laning but devastating teamfight presence with ultimate.",
  },
  {
    id: 'samira',
    name: "Samira",
    title: "The Desert Rose",
    role: ["Marksman", "Assassin"],
    difficulty: "High",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Samira_0.jpg",
    tags: ["All-in", "Reset", "Combo"],
    synergies: ["engage"],
    counters: ["assassin"],
    description: "Requires a hard engage support to function. Blocks projectiles with W, making her good against skillshot reliance.",
  },
  {
    id: 'zeri',
    name: "Zeri",
    title: "The Spark of Zaun",
    role: ["Marksman"],
    difficulty: "High",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zeri_0.jpg",
    tags: ["High Mobility", "Scaling", "Teamfight"],
    synergies: ["enchanter", "engage"],
    counters: ["tank"],
    description: "Extremely mobile ADC. Ultimate stacks movement speed in teamfights. Strong with enchanters.",
  },
  {
    id: 'karthus',
    name: "Karthus",
    title: "The Deathsinger",
    role: ["Mage"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Karthus_0.jpg",
    tags: ["APC", "Global", "Scaling"],
    synergies: ["enchanter", "poke"],
    counters: ["assassin"],
    description: "APC with global ultimate. Farms safely and scales well. Passive allows damage after death.",
  },
  {
    id: 'kalista',
    name: "Kalista",
    title: "The Spear of Vengeance",
    role: ["Marksman"],
    difficulty: "High",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kalista_0.jpg",
    tags: ["Mobility", "Objective Control", "Duo Synergy"],
    synergies: ["engage"],
    counters: ["tank"],
    description: "Bound to support with Oathsworn. Insane mobility and objective control with rend. Needs coordinated support.",
  },
  {
    id: 'nilah',
    name: "Nilah",
    title: "The Joy Unbound",
    role: ["Marksman", "Fighter"],
    difficulty: "High",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nilah_0.jpg",
    tags: ["Melee", "All-in", "Duo XP"],
    synergies: ["enchanter", "engage"],
    counters: ["poke"],
    description: "Melee ADC with shared XP passive. Strong with enchanter supports who benefit from her passive.",
  },
  {
    id: 'kogmaw',
    name: "Kog'Maw",
    title: "The Mouth of the Abyss",
    role: ["Marksman", "Mage"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/KogMaw_0.jpg",
    tags: ["Tank Shred", "Hypercarry", "Late Game"],
    synergies: ["enchanter"],
    counters: ["tank"],
    description: "Ultimate tank shredder. Zero mobility but massive damage with W. Needs heavy protection.",
  },
  {
    id: 'seraphine',
    name: "Seraphine",
    title: "The Starry-Eyed Songstress",
    role: ["Mage", "Support"],
    difficulty: "Low",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Seraphine_0.jpg",
    tags: ["APC", "Utility", "Teamfight"],
    synergies: ["engage", "enchanter"],
    counters: ["assassin"],
    description: "APC with strong utility and teamfight. Works as both carry and support depending on build.",
  },
  {
    id: 'ziggs',
    name: "Ziggs",
    title: "The Hexplosives Expert",
    role: ["Mage"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ziggs_0.jpg",
    tags: ["APC", "Siege", "Waveclear"],
    synergies: ["poke", "enchanter"],
    counters: ["assassin"],
    description: "APC with excellent siege and waveclear. Can take towers with W passive. Safe laning.",
  },
  {
    id: 'aurelionsol',
    name: "Aurelion Sol",
    title: "The Star Forger",
    role: ["Mage"],
    difficulty: "High",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/AurelionSol_0.jpg",
    tags: ["APC", "Scaling", "Teamfight"],
    synergies: ["enchanter"],
    counters: ["assassin"],
    description: "APC with massive scaling and teamfight presence. Stacks infinitely with abilities.",
  },
  {
    id: 'cassiopeia',
    name: "Cassiopeia",
    title: "The Serpent's Embrace",
    role: ["Mage"],
    difficulty: "High",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Cassiopeia_0.jpg",
    tags: ["APC", "DPS", "Anti-Dive"],
    synergies: ["engage"],
    counters: ["tank"],
    description: "High DPS mage with grounding and anti-dive ultimate. Strong vs melee threats.",
  },
  {
    id: 'corki',
    name: "Corki",
    title: "The Daring Bombardier",
    role: ["Marksman", "Mage"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Corki_0.jpg",
    tags: ["Hybrid", "Burst", "Poke"],
    synergies: ["poke", "enchanter"],
    counters: ["assassin"],
    description: "Hybrid damage dealer with strong poke and burst. Package provides map mobility.",
  },
  {
    id: 'heimerdinger',
    name: "Heimerdinger",
    title: "The Revered Inventor",
    role: ["Mage"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Heimerdinger_0.jpg",
    tags: ["APC", "Zone Control", "Push"],
    synergies: ["enchanter"],
    counters: ["poke"],
    description: "Zone control mage with turrets. Dominates lane but weak to being all-inned.",
  },
  {
    id: 'hwei',
    name: "Hwei",
    title: "The Visionary",
    role: ["Mage"],
    difficulty: "High",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Hwei_0.jpg",
    tags: ["APC", "Poke", "Utility"],
    synergies: ["enchanter", "poke"],
    counters: ["assassin"],
    description: "Versatile mage with multiple spell options. Strong poke and utility.",
  },
  {
    id: 'lux',
    name: "Lux",
    title: "The Lady of Luminosity",
    role: ["Mage"],
    difficulty: "Low",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lux_0.jpg",
    tags: ["APC", "Burst", "Poke"],
    synergies: ["poke", "engage"],
    counters: ["assassin"],
    description: "APC with long range burst and CC. Safe laning with shield utility.",
  },
  {
    id: 'mel',
    name: "Mel",
    title: "The Medarda",
    role: ["Mage", "Support"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Mel_0.jpg",
    tags: ["APC", "Utility", "Enchanter"],
    synergies: ["enchanter", "engage"],
    counters: ["assassin"],
    description: "New champion with enchanter-like utility while dealing damage.",
  },
  {
    id: 'senna',
    name: "Senna",
    title: "The Redeemer",
    role: ["Marksman", "Support"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Senna_0.jpg",
    tags: ["ADC", "Utility", "Scaling"],
    synergies: ["engage"],
    counters: ["assassin"],
    description: "Scaling ADC with infinite range growth. Strong utility with heal and global ultimate.",
  },
  {
    id: 'swain',
    name: "Swain",
    title: "The Noxian Grand General",
    role: ["Mage", "Fighter"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Swain_0.jpg",
    tags: ["APC", "Drain Tank", "CC"],
    synergies: ["engage"],
    counters: ["tank"],
    description: "Drain tank mage with CC. Thrives in extended fights with ultimate.",
  },
  {
    id: 'syndra',
    name: "Syndra",
    title: "The Dark Sovereign",
    role: ["Mage"],
    difficulty: "High",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Syndra_0.jpg",
    tags: ["APC", "Burst", "Control"],
    synergies: ["poke", "enchanter"],
    counters: ["assassin"],
    description: "High burst mage with strong pick potential. Scales with orbs collected.",
  },
  {
    id: 'veigar',
    name: "Veigar",
    title: "The Tiny Master of Evil",
    role: ["Mage"],
    difficulty: "Low",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Veigar_0.jpg",
    tags: ["APC", "Scaling", "Burst"],
    synergies: ["engage"],
    counters: ["assassin"],
    description: "Infinite scaling mage with cage CC. Execute ultimate on low HP targets.",
  },
  {
    id: 'velkoz',
    name: "Vel'Koz",
    title: "The Eye of the Void",
    role: ["Mage"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Velkoz_0.jpg",
    tags: ["APC", "Poke", "True Damage"],
    synergies: ["poke", "enchanter"],
    counters: ["assassin"],
    description: "Artillery mage with true damage passive. Strong poke and teamfight ultimate.",
  },
  {
    id: 'xerath',
    name: "Xerath",
    title: "The Magus Ascendant",
    role: ["Mage"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Xerath_0.jpg",
    tags: ["APC", "Artillery", "Poke"],
    synergies: ["poke"],
    counters: ["assassin"],
    description: "Long range artillery mage. Safe laning with massive poke range.",
  },
  {
    id: 'yasuo',
    name: "Yasuo",
    title: "The Unforgiven",
    role: ["Fighter", "Assassin"],
    difficulty: "High",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yasuo_0.jpg",
    tags: ["Melee ADC", "Crit", "Windwall"],
    synergies: ["engage"],
    counters: ["poke"],
    description: "Melee carry with windwall and knockup synergy. High skill cap.",
  },
  {
    id: 'yunara',
    name: "Yunara",
    title: "The Wildflower",
    role: ["Mage"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yunara_0.jpg",
    tags: ["APC", "Control", "Utility"],
    synergies: ["enchanter"],
    counters: ["assassin"],
    description: "New champion with plant-based abilities and zone control.",
  },
  {
    id: 'brand',
    name: "Brand",
    title: "The Burning Vengeance",
    role: ["Mage"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Brand_0.jpg",
    tags: ["APC", "Burst", "AOE"],
    synergies: ["engage"],
    counters: ["tank"],
    description: "High AOE damage mage with % max HP burn. Strong in teamfights.",
  },
  {
    id: 'zyra',
    name: "Zyra",
    title: "Rise of the Thorns",
    role: ["Mage"],
    difficulty: "Medium",
    image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zyra_0.jpg",
    tags: ["APC", "Zone Control", "Plants"],
    synergies: ["poke", "engage"],
    counters: ["assassin"],
    description: "Zone control mage with plant summons. Strong laning and teamfight presence.",
  },
];

export const adcs: Champion[] = adcBase.map((champion) => ({
  ...champion,
  imageSmall: getChampionSquareIcon(champion.name),
}));

const supportBase: Array<Omit<SupportChampion, "imageSmall">> = [
  { id: 'nami', name: 'Nami', type: 'enchanter', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nami_0.jpg" },
  { id: 'thresh', name: 'Thresh', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Thresh_0.jpg" },
  { id: 'lulu', name: 'Lulu', type: 'enchanter', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lulu_0.jpg" },
  { id: 'lux', name: 'Lux', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lux_0.jpg" },
  { id: 'karma', name: 'Karma', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Karma_0.jpg" },
  { id: 'nautilus', name: 'Nautilus', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nautilus_0.jpg" },
  { id: 'bard', name: 'Bard', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Bard_0.jpg" },
  { id: 'blitzcrank', name: 'Blitzcrank', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcrank_0.jpg" },
  { id: 'soraka', name: 'Soraka', type: 'enchanter', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Soraka_0.jpg" },
  { id: 'rakan', name: 'Rakan', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rakan_0.jpg" },
  { id: 'alistar', name: 'Alistar', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg" },
  { id: 'janna', name: 'Janna', type: 'enchanter', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Janna_0.jpg" },
  { id: 'leona', name: 'Leona', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Leona_0.jpg" },
  { id: 'neeko', name: 'Neeko', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Neeko_0.jpg" },
  { id: 'seraphine', name: 'Seraphine', type: 'enchanter', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Seraphine_0.jpg" },
  { id: 'morgana', name: 'Morgana', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Morgana_0.jpg" },
  { id: 'senna', name: 'Senna', type: 'enchanter', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Senna_0.jpg" },
  { id: 'rell', name: 'Rell', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rell_0.jpg" },
  { id: 'poppy', name: 'Poppy', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Poppy_0.jpg" },
  { id: 'sona', name: 'Sona', type: 'enchanter', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sona_0.jpg" },
  { id: 'pantheon', name: 'Pantheon', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pantheon_0.jpg" },
  { id: 'velkoz', name: "Vel'Koz", type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Velkoz_0.jpg" },
  { id: 'zyra', name: 'Zyra', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zyra_0.jpg" },
  { id: 'zilean', name: 'Zilean', type: 'enchanter', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zilean_0.jpg" },
  { id: 'yuumi', name: 'Yuumi', type: 'enchanter', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yuumi_0.jpg" },
  { id: 'pyke', name: 'Pyke', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pyke_0.jpg" },
  { id: 'milio', name: 'Milio', type: 'enchanter', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Milio_0.jpg" },
  { id: 'xerath', name: 'Xerath', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Xerath_0.jpg" },
  { id: 'braum', name: 'Braum', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Braum_0.jpg" },
  { id: 'taric', name: 'Taric', type: 'enchanter', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Taric_0.jpg" },
  { id: 'renata', name: 'Renata Glasc', type: 'enchanter', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Renata_0.jpg" },
  { id: 'tahmkench', name: 'Tahm Kench', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/TahmKench_0.jpg" },
  { id: 'swain', name: 'Swain', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Swain_0.jpg" },
  { id: 'brand', name: 'Brand', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Brand_0.jpg" },
  { id: 'maokai', name: 'Maokai', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Maokai_0.jpg" },
  { id: 'amumu', name: 'Amumu', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Amumu_0.jpg" },
  { id: 'anivia', name: 'Anivia', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Anivia_0.jpg" },
  { id: 'annie', name: 'Annie', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Annie_0.jpg" },
  { id: 'ashe', name: 'Ashe', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_0.jpg" },
  { id: 'aurelionsol', name: 'Aurelion Sol', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/AurelionSol_0.jpg" },
  { id: 'camille', name: 'Camille', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Camille_0.jpg" },
  { id: 'chogath', name: "Cho'Gath", type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Chogath_0.jpg" },
  { id: 'elise', name: 'Elise', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Elise_0.jpg" },
  { id: 'fiddlesticks', name: 'Fiddlesticks', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_0.jpg" },
  { id: 'galio', name: 'Galio', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Galio_0.jpg" },
  { id: 'gragas', name: 'Gragas', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gragas_0.jpg" },
  { id: 'heimerdinger', name: 'Heimerdinger', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Heimerdinger_0.jpg" },
  { id: 'hwei', name: 'Hwei', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Hwei_0.jpg" },
  { id: 'ivern', name: 'Ivern', type: 'enchanter', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ivern_0.jpg" },
  { id: 'jarvaniv', name: 'Jarvan IV', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/JarvanIV_0.jpg" },
  { id: 'kennen', name: 'Kennen', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kennen_0.jpg" },
  { id: 'kogmaw', name: "Kog'Maw", type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/KogMaw_0.jpg" },
  { id: 'leblanc', name: 'LeBlanc', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Leblanc_0.jpg" },
  { id: 'lissandra', name: 'Lissandra', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lissandra_0.jpg" },
  { id: 'malphite', name: 'Malphite', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Malphite_0.jpg" },
  { id: 'mel', name: 'Mel', type: 'enchanter', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Mel_0.jpg" },
  { id: 'nidalee', name: 'Nidalee', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nidalee_0.jpg" },
  { id: 'nunu', name: 'Nunu', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nunu_0.jpg" },
  { id: 'ornn', name: 'Ornn', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ornn_0.jpg" },
  { id: 'quinn', name: 'Quinn', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Quinn_0.jpg" },
  { id: 'rammus', name: 'Rammus', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rammus_0.jpg" },
  { id: 'rengar', name: 'Rengar', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rengar_0.jpg" },
  { id: 'rumble', name: 'Rumble', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rumble_0.jpg" },
  { id: 'sejuani', name: 'Sejuani', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sejuani_0.jpg" },
  { id: 'sett', name: 'Sett', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sett_0.jpg" },
  { id: 'shaco', name: 'Shaco', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shaco_0.jpg" },
  { id: 'shen', name: 'Shen', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shen_0.jpg" },
  { id: 'singed', name: 'Singed', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Singed_0.jpg" },
  { id: 'sion', name: 'Sion', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sion_0.jpg" },
  { id: 'skarner', name: 'Skarner', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Skarner_0.jpg" },
  { id: 'sylas', name: 'Sylas', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sylas_0.jpg" },
  { id: 'taliyah', name: 'Taliyah', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Taliyah_0.jpg" },
  { id: 'teemo', name: 'Teemo', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Teemo_0.jpg" },
  { id: 'trundle', name: 'Trundle', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Trundle_0.jpg" },
  { id: 'twistedfate', name: 'Twisted Fate', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/TwistedFate_0.jpg" },
  { id: 'twitch', name: 'Twitch', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Twitch_0.jpg" },
  { id: 'veigar', name: 'Veigar', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Veigar_0.jpg" },
  { id: 'vex', name: 'Vex', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vex_0.jpg" },
  { id: 'wukong', name: 'Wukong', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MonkeyKing_0.jpg" },
  { id: 'zac', name: 'Zac', type: 'engage', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zac_0.jpg" },
  { id: 'ziggs', name: 'Ziggs', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ziggs_0.jpg" },
  { id: 'zoe', name: 'Zoe', type: 'poke', image: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zoe_0.jpg" },
];

export const supports: SupportChampion[] = supportBase.map((support) => ({
  ...support,
  imageSmall: getChampionSquareIcon(support.name),
}));

const enemyBase: Array<Omit<Champion, "imageSmall">> = [
  { id: 'enemy_zed', name: 'Zed', title: 'Master of Shadows', role: ['Assassin'], difficulty: 'High', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zed_0.jpg', tags: ['Assassin', 'Burst'], synergies: [], counters: [], description: '' },
  { id: 'enemy_akali', name: 'Akali', title: 'The Rogue Assassin', role: ['Assassin'], difficulty: 'High', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg', tags: ['Assassin', 'Burst'], synergies: [], counters: [], description: '' },
  { id: 'enemy_darius', name: 'Darius', title: 'The Hand of Noxus', role: ['Fighter'], difficulty: 'Medium', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Darius_0.jpg', tags: ['Tanky', 'Burst'], synergies: [], counters: [], description: '' },
  { id: 'enemy_jayce', name: 'Jayce', title: 'The Defender of Tomorrow', role: ['Fighter', 'Poke'], difficulty: 'High', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jayce_0.jpg', tags: ['Poke', 'Range'], synergies: [], counters: [], description: '' },
  { id: 'enemy_sion', name: 'Sion', title: 'The Undead Juggernaut', role: ['Tank'], difficulty: 'Medium', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sion_0.jpg', tags: ['Tank', 'HP'], synergies: [], counters: [], description: '' },
  { id: 'enemy_ornn', name: 'Ornn', title: 'The Fire below the Mountain', role: ['Tank'], difficulty: 'Medium', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ornn_0.jpg', tags: ['Tank', 'CC'], synergies: [], counters: [], description: '' },
  { id: 'enemy_maokai', name: 'Maokai', title: 'The Twisted Treant', role: ['Tank'], difficulty: 'Low', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Maokai_0.jpg', tags: ['Tank', 'CC'], synergies: [], counters: [], description: '' },
];

export const enemies: Champion[] = enemyBase.map((champion) => ({
  ...champion,
  imageSmall: getChampionSquareIcon(champion.name),
}));

export interface BotLaner {
  id: string;
  name: string;
  image: string;
  imageSmall: string;
}

const botLanerBase: Array<Omit<BotLaner, "imageSmall">> = [
  { id: 'aphelios', name: 'Aphelios', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aphelios_0.jpg' },
  { id: 'ashe', name: 'Ashe', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_0.jpg' },
  { id: 'aurelionsol', name: 'Aurelion Sol', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/AurelionSol_0.jpg' },
  { id: 'brand', name: 'Brand', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Brand_0.jpg' },
  { id: 'caitlyn', name: 'Caitlyn', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Caitlyn_0.jpg' },
  { id: 'cassiopeia', name: 'Cassiopeia', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Cassiopeia_0.jpg' },
  { id: 'corki', name: 'Corki', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Corki_0.jpg' },
  { id: 'draven', name: 'Draven', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Draven_0.jpg' },
  { id: 'ezreal', name: 'Ezreal', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ezreal_0.jpg' },
  { id: 'heimerdinger', name: 'Heimerdinger', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Heimerdinger_0.jpg' },
  { id: 'hwei', name: 'Hwei', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Hwei_0.jpg' },
  { id: 'jhin', name: 'Jhin', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jhin_0.jpg' },
  { id: 'jinx', name: 'Jinx', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_0.jpg' },
  { id: 'kaisa', name: "Kai'Sa", image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kaisa_0.jpg' },
  { id: 'kalista', name: 'Kalista', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kalista_0.jpg' },
  { id: 'karthus', name: 'Karthus', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Karthus_0.jpg' },
  { id: 'kogmaw', name: "Kog'Maw", image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/KogMaw_0.jpg' },
  { id: 'lucian', name: 'Lucian', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lucian_0.jpg' },
  { id: 'lux', name: 'Lux', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lux_0.jpg' },
  { id: 'mel', name: 'Mel', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Mel_0.jpg' },
  { id: 'missfortune', name: 'Miss Fortune', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MissFortune_0.jpg' },
  { id: 'nilah', name: 'Nilah', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nilah_0.jpg' },
  { id: 'samira', name: 'Samira', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Samira_0.jpg' },
  { id: 'senna', name: 'Senna', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Senna_0.jpg' },
  { id: 'seraphine', name: 'Seraphine', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Seraphine_0.jpg' },
  { id: 'sivir', name: 'Sivir', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sivir_0.jpg' },
  { id: 'smolder', name: 'Smolder', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Smolder_0.jpg' },
  { id: 'swain', name: 'Swain', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Swain_0.jpg' },
  { id: 'syndra', name: 'Syndra', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Syndra_0.jpg' },
  { id: 'tristana', name: 'Tristana', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Tristana_0.jpg' },
  { id: 'twitch', name: 'Twitch', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Twitch_0.jpg' },
  { id: 'varus', name: 'Varus', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Varus_0.jpg' },
  { id: 'vayne', name: 'Vayne', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vayne_0.jpg' },
  { id: 'veigar', name: 'Veigar', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Veigar_0.jpg' },
  { id: 'velkoz', name: "Vel'Koz", image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Velkoz_0.jpg' },
  { id: 'xayah', name: 'Xayah', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Xayah_0.jpg' },
  { id: 'xerath', name: 'Xerath', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Xerath_0.jpg' },
  { id: 'yasuo', name: 'Yasuo', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yasuo_0.jpg' },
  { id: 'yunara', name: 'Yunara', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yunara_0.jpg' },
  { id: 'zeri', name: 'Zeri', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zeri_0.jpg' },
  { id: 'ziggs', name: 'Ziggs', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ziggs_0.jpg' },
  { id: 'zyra', name: 'Zyra', image: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zyra_0.jpg' },
];

export const botLaners: BotLaner[] = botLanerBase.map((champion) => ({
  ...champion,
  imageSmall: getChampionSquareIcon(champion.name),
}));
